#version: '3.8'
#
#services:
#  app:
#    build: .
#    ports:
#      - "8000:5000"
#    volumes:
#      - "./data:/app/data"
#    depends_on:
#      - database
#
#  database:
#    image: "postgres:latest"
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=flask_app
#    volumes:
#      - "./data/postgres:/var/lib/postgresql/data"
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: flask_app
    ports:
      - "5432:5432"
