version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - "./data:/app/data"
    depends_on:
      - database
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flask_app
    networks:
      - flask_network

  database:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flask_app
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    networks:
      - flask_network
networks:
  flask_network:
    driver: bridge